name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, reopened]

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/pr-title-checker-config.json
